# Generated by Django 3.1.5 on 2021-02-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transferTablo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=40)),
                ('soyadi', models.CharField(max_length=40)),
                ('transferDetay', models.TextField()),
                ('resim', models.CharField(max_length=50)),
                ('yuklemeTarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
